### ISSUE TITLE
Tidy task for updating meta data and README

### ISSUE THREAD

**Issue by kristenwomack** [Azure-Samples/agent-openai-python-prompty#31]
Updates:

- [x] update repo name in `azure.yaml` and meta data `template` attribute 
- [x] remove the step for creating an azd env 
- [ ] optional: add a note in the README that if they want a second env, here's how to do it

**Comment by marlenezw** [comment]
Removed the step for creating an env
